import mysql.connector as pysql
from mysql.connector import errorcode

connection = pysql.connect(user='root',host='localhost',database='HisaabDB')

