import mysql.connector
from mysql.connector import errorcode

connection = pysql.connect(user='root',host='localhost',database='HisaabDB')

